version: '3.8'

services:
  nginx_test:
    # image: nginx:latest
    build:
      context: .
    container_name: react-spa-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    restart: always

  # frontend:
  #   build:
  #     context: .
  #   container_name: frontend_app
