services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data

  adminer_prod:
    image: adminer
    container_name: prod_adminer
    restart: always
    ports:
      - 6080:8080

  rails:
    build:
      context: ./backend
    container_name: rails_app
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bundle exec puma -C config/puma.rb
    expose:
      - "3000"

  sidekiq:
    build:
      context: ./backend
    container_name: sidekiq_worker
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    depends_on:
      - rails

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx_proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - rails

volumes:
  postgres_data:
  redis_data:
