@startuml
object Пользователь 
object Роль 
object Автомобили
object Заказ
object Груз
object Склад
object Доставка
object Маршрут

Пользователь -- Роль
Пользователь --* Автомобили
Пользователь --* Заказ
Заказ --* Груз
Заказ --* Склад
Склад -- Маршрут
Маршрут -- Пользователь
Маршрут --* Доставка
Доставка -- Пользователь
Доставка --* Груз

@enduml